meta_product_name: "Check"
meta_title: "Check - Balanced Mind, Balanced Body"
meta_description: "Correct your posture"
meta_image: "metaimage.png"                       # should exist in `app/assets/images/`
twitter_account: "@check_posture"
